### ISSUE TITLE
Re-design application cover tile

### ISSUE THREAD

**Issue by miyconst** [StarcounterSamples/AppStoreClient#24]
Umbrella issue: https://github.com/Starcounter/RebelsLounge/issues/8

Requires images and sizes from @Starcounter-Jack.

**Comment by andwah** [comment]
The large appicon will be 1024 x 1024 pixels  and the small 57 x 57 pixels.
see ***App Icon (required for iOS apps)***
Screenshots will be 16:10 aspect ratio
see ***Mac (OS X) Screenshots*** at link below

https://developer.apple.com/library/ios/documentation/LanguagesUtilities/Conceptual/iTunesConnect_Guide/Appendices/Properties.html#//apple_ref/doc/uid/TP40011225-CH26-SW13

**Comment by miyconst** [comment]
Closing the issue. The new design was accepted.
